#!/usr/bin/env python3
"""
make_queue.py  —  build the bulk-import worklist for ManuscriptDB

Scans manuscripts/ for the papyri you already have, then writes
import_queue.txt listing the Gregory-Aland numbers that are still missing,
so the continuous-import workflow always knows what's left to do.

Usage:
    python make_queue.py                 # gaps in P1..P141 (default)
    python make_queue.py --max 150       # extend the upper bound
    python make_queue.py --master ga_list.txt   # use an explicit list of valid IDs
    python make_queue.py --include-existing      # write ALL targets, marking done ones

The continuous-import prompt reads import_queue.txt top to bottom: lines that
start with '#' or 'DONE ' are skipped, so you (or the agent) can tick items off
by prefixing them with 'DONE '.
"""

import argparse, glob, os, re

HERE = os.path.dirname(os.path.abspath(__file__))
MANUSCRIPTS_DIR = os.path.join(HERE, "manuscripts")
QUEUE_PATH = os.path.join(HERE, "import_queue.txt")


def existing_ids():
    ids = set()
    for path in glob.glob(os.path.join(MANUSCRIPTS_DIR, "P*.txt")):
        m = re.match(r"(P\d+)", os.path.basename(path))
        if m:
            ids.add(m.group(1))
    return ids


def target_ids(max_n, master):
    if master:
        with open(master, encoding="utf-8") as f:
            out = []
            for line in f:
                m = re.search(r"P\d+", line)
                if m:
                    out.append(m.group(0))
        return out
    return [f"P{n}" for n in range(1, max_n + 1)]


def main():
    p = argparse.ArgumentParser(description="Build the ManuscriptDB import worklist.")
    p.add_argument("--max", type=int, default=141,
                   help="Highest Gregory-Aland number to consider (default 141).")
    p.add_argument("--master", default="",
                   help="Optional file listing valid IDs (one P-number per line) "
                        "instead of a simple 1..max range.")
    p.add_argument("--include-existing", action="store_true",
                   help="Write every target, prefixing already-imported ones with 'DONE '.")
    p.add_argument("--out", default=QUEUE_PATH, help="Output path (default import_queue.txt).")
    args = p.parse_args()

    have = existing_ids()
    targets = target_ids(args.max, args.master)

    def num(pid):
        return int(pid[1:])

    targets = sorted(set(targets), key=num)
    missing = [t for t in targets if t not in have]

    lines = [
        "# ManuscriptDB import worklist — generated by make_queue.py",
        "# One Gregory-Aland number per line. Lines starting with '#' or 'DONE ' are skipped.",
        f"# Already imported: {len(have)}   |   Still missing: {len(missing)}",
        "#",
    ]
    if args.include_existing:
        for t in targets:
            lines.append(f"DONE {t}" if t in have else t)
    else:
        lines.extend(missing)

    with open(args.out, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    print(f"Have {len(have)} manuscripts. {len(missing)} missing.")
    print("Missing:", ", ".join(missing) if missing else "(none — collection complete!)")
    print(f"Wrote worklist to {args.out}")


if __name__ == "__main__":
    main()
